---
title: "Client Report - [Finding Names]"
subtitle: "Course DS 250"
execute:
    warning: false
author: "[Brooke Escue]"
format:
  html:

    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
```



```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here

names = pd.read_csv("names_year.txt", parse_dates=['year'])

```



```{python}
#| label: GQ1
#| code-summary: Read and format data
# Include and execute your code here
names.filter(["name", "Total"])
names.head(n=10)


```



```{python}
#| label: GQ2
#| code-summary: Read and format data
# This filters out our names and makes it unique 

names.filter(["name"]).nunique()
```


```{python}
#| label: GQ3
#| code-summary: Read and format data
# This finds the max and min of the years 

names.filter(["year", "Total"]).min()

names.filter(["year", "Total"]).max()


```

## GRAND QUESTION 1

How does your name at your birth year compare to its use historically?

The name Brooke was starting to decline.  However, it was still popular in 2001.  

```{python}
# Find names that only are Brooke

brooke= (names
.query('name == "Brooke"'))
```


```{python}
# get rid of the commma in year and make a title 

chart = (alt.Chart(brooke).encode(
    x =alt.X ("year", title = "year"), 
    y= alt.Y ("Total")
).mark_line()

) 

```


```{python}
# How to mark Brookes birthyear 

bday_data = brooke.query('year == 2001')
bday_data

bday_chart = (alt.Chart(bday_data).encode(
    x = alt.X("year", title = "Year"), 
    y = alt.Y("Total")
).mark_point(color = "red")
)

chart + bday_chart
```

## Grand Question Two 

If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?

Based on the graph, I found that her age is around 30 years old.  This is because the name was most popular at 1990. 


```{python}

brit = (names
.query('name == "Brittany"'))

brit = (names
.query('name == "Brittany"'))



```




```{python}

# get rid of the commma in year and make a title 

phone = (alt.Chart(brit).encode(
    x =alt.X ("year", title = "year"), 
    y= alt.Y ("Total")
).mark_bar()

) 
phone
```

## Grand Question Three

Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?

Looking at the graph, Mart seemed to have the highest usage from 1910-2015.  Paul had the second highest usage.  It looks like all four of these names have been declining since the mid 1950s

```{python}
# Make a chart with four different christian names and try to make it from 1920-2000

names_christian = (names.query('name == ["Mary", "Martha", "Peter", "Paul"]').query("year >= 1920 & year <= 2000"))



christian = (alt.Chart(names_christian).mark_line().encode(
    x = alt.X("year"),
    y = alt.Y("Total"), 
    color = alt.Color("name")
    )
)

christian 
```


## Grand Question 4
Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?

I chose the Wizard of Oz and I picked the name Dorothy.  This was a popular movie and I wanted to see of there was an increase of the name.  Looking at our graph I found that the name was steadily decreasing and the movie appeared to not have an affect on the name.  


```{python}
movie_names = (names
.query('name == "Dorothy"'))

Dorothy_chart = (alt.Chart(movie_names).mark_line().encode(
    x = alt.X("year"), 
    y = alt.Y("Total")

)
)

release_date = movie_names.query('year == 1939')
release_date


release_chart = (alt.Chart(release_date).encode(
    x = alt.X("year")
).mark_rule(color = "green")
)

release_chart + Dorothy_chart
```



```{python}


```
